- name: install mysql packages
  apt: name={{ item }} state=latest
  with_items:
    - mysql-server
    - mysql-client
    - libmysql++-dev
    - python-mysqldb
- name: start mysqld
  service: name=mysql state=restarted enabled=yes
