---
- include: setup-Ubuntu14.04.yml
  when: 
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '14.04' 
- include: setup-CentOS7.yml
  when: 
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7' 
- include: setup-Amazon.yml
  when: 
    - ansible_distribution == 'Amazon'
